/**
 * MCP-bundel voor Lovable-projecten op Supabase: bouwen, bewaken en herstellen.
 *
 * ⚠️ BOUWTIJD-module. Draait in Node (of Deno) tijdens build, pre-commit-hook en CI,
 * nooit in een edge function. Gebruikt enkel `node:`-modules; esbuild en
 * `@lovable.dev/mcp-js` komen uit de `node_modules` van het project zelf. Bewust: de
 * bundel moet byte-gelijk zijn aan wat de Lovable-plugin met de esbuild-versie van
 * het project bouwt, dus een eigen, gepinde esbuild zou een vals verschil geven.
 *
 * Waarom dit bestaat. `supabase/functions/mcp/index.ts` is GEGENEREERD uit
 * `src/lib/mcp/`. Drie stille faalvormen, alle drie echt gebeurd:
 *
 * 1. Handwerk in de bundel wordt bij de volgende build gewist.
 * 2. Op Windows gaf de plugin esbuild een absoluut pad (`C:\...`) en besliste met
 *    `startsWith(".") || startsWith("/")` of een import lokaal was; de hele MCP werd
 *    als npm-extern weggezet en er bleef een stub van vier regels over.
 * 3. Zonder de AUTO-GENERATED-banner laat de plugin het bestand met rust en
 *    veroudert de bundel stil.
 *
 * Gebruik in een project (wrappers van enkele regels):
 *
 * ```js
 * // scripts/bundle-mcp.mjs
 * import { fileURLToPath } from "node:url";
 * import { bouwMcpBundel, controleerMcpBundel } from "@holie/tools/mcp-bundel";
 * const root = fileURLToPath(new URL("..", import.meta.url));
 * if (process.argv.includes("--check")) {
 *   const { inOrde, fouten } = await controleerMcpBundel(root);
 *   for (const f of fouten) console.error(`- ${f}`);
 *   process.exit(inOrde ? 0 : 1);
 * }
 * await bouwMcpBundel(root);
 * ```
 *
 * @module
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { createRequire } from "node:module";

/**
 * Exact de banner van de plugin. Die overschrijft enkel bestanden die ermee BEGINNEN,
 * dus `// @ts-nocheck` staat erachter, niet op regel 1.
 */
export const BANNER: string =
  "// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.\n" +
  "// To take ownership, delete this banner line; the plugin then leaves the file alone.\n" +
  "// @ts-nocheck\n" +
  "// supabase function: mcp\n" +
  "// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.\n";

const BANNER_KERN = "AUTO-GENERATED by @lovable.dev/mcp-js";

/** Relatief aan de projectroot, altijd met `/`. */
export const BUNDEL_PAD = "supabase/functions/mcp/index.ts";
export const BRON_MAP = "src/lib/mcp";

/**
 * De entry van de bundel. De MCP-import is RELATIEF (`./src/...`) met `resolveDir` op
 * de root: nooit een absoluut pad aan esbuild geven, dat was faalvorm 2.
 */
export const ENTRY: string = `import mcp from "./${BRON_MAP}/index.ts";\n` +
  `import { createSupabaseHandler } from "@lovable.dev/mcp-js/stacks/supabase";\n` +
  `Deno.serve(createSupabaseHandler(mcp, { functionName: "mcp" }));\n`;

/**
 * Is dit importpad een lokaal bestand? Ook Windows-paden (`C:\`, `C:/`, `\\server`)
 * tellen als lokaal, zodat een absoluut pad nooit als npm-pakket wordt weggezet.
 */
export function isLokaalPad(p: string): boolean {
  return p.startsWith(".") || p.startsWith("/") || /^[A-Za-z]:[\\/]/.test(p) ||
    p.startsWith("\\\\");
}

/** Bare import naar een `npm:`-specifier met de versie uit package.json. */
export function npmSpecifier(
  bare: string,
  versies: Record<string, string>,
  sdkVersie: string,
): string {
  const naam = bare.startsWith("@")
    ? bare.split("/").slice(0, 2).join("/")
    : bare.split("/")[0];
  const subpad = bare.slice(naam.length);
  if (naam === "@lovable.dev/mcp-js") {
    return `npm:${naam}@${sdkVersie}${subpad}`;
  }
  const range = versies[naam];
  const versie = range && /^[\dv^~>=]|^latest$/.test(range) ? range : undefined;
  return versie ? `npm:${naam}@${versie}${subpad}` : `npm:${naam}${subpad}`;
}

/**
 * Vite's `loadEnv("production", root, "VITE_")` in het klein, met de terugval van de
 * plugin op `supabase/config.toml` voor de projectref (in CI staat er geen .env).
 */
export function leesEnv(root: string): Record<string, string | boolean> {
  const env: Record<string, string | boolean> = {
    MODE: "production",
    BASE_URL: "/",
    DEV: false,
    PROD: true,
    SSR: false,
  };
  for (
    const naam of [
      ".env",
      ".env.production",
      ".env.local",
      ".env.production.local",
    ]
  ) {
    let tekst: string;
    try {
      tekst = readFileSync(join(root, naam), "utf8");
    } catch {
      continue;
    }
    for (const regel of tekst.split(/\r?\n/)) {
      const m = /^\s*(?:export\s+)?([A-Za-z_][\w]*)\s*=\s*(.*)$/.exec(regel);
      if (!m || !m[1].startsWith("VITE_")) continue;
      env[m[1]] = m[2].trim().replace(/^(['"])(.*)\1$/, "$2");
    }
  }
  if (!env.VITE_SUPABASE_PROJECT_ID) {
    try {
      const toml = readFileSync(join(root, "supabase", "config.toml"), "utf8");
      const m = /^\s*project_id\s*=\s*["']([^"']+)["']/m.exec(toml);
      if (m) env.VITE_SUPABASE_PROJECT_ID = m[1];
    } catch {
      // geen config.toml: bouwMcpBundel meldt het
    }
  }
  return env;
}

/**
 * De plugin schrijft de bundel zonder `// @ts-nocheck`, ons script met; en na een
 * checkout met `core.autocrlf` staan er CRLF's. Beide zijn geen echt verschil.
 */
export function normaliseer(tekst = ""): string {
  return tekst.replace(/\r\n/g, "\n").replace(/^\/\/ @ts-nocheck\n/m, "");
}

/** Alle `name: "tool_naam"` in een brontekst. */
export function toolnamenUitTekst(tekst: string): string[] {
  return [...tekst.matchAll(/\bname:\s*["']([a-z][a-z0-9_]*)["']/g)].map((m) =>
    m[1]
  );
}

function toolnamenUitMap(dir: string): Set<string> {
  const namen = new Set<string>();
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) toolnamenUitMap(p).forEach((n) => namen.add(n));
    else if (/\.(ts|tsx|js|mjs)$/.test(e.name)) {
      toolnamenUitTekst(readFileSync(p, "utf8")).forEach((n) => namen.add(n));
    }
  }
  return namen;
}

/**
 * De controles die geen build nodig hebben: banner op regel 1 en elke toolnaam uit
 * de bron aanwezig. Een Windows-stub valt hier al op.
 */
export function controleerInhoud(
  bundel: string,
  toolnamen: Iterable<string>,
): string[] {
  const fouten: string[] = [];
  if (!(bundel.split(/\r?\n/, 1)[0] ?? "").includes(BANNER_KERN)) {
    fouten.push(
      `Banner "${BANNER_KERN}" ontbreekt op regel 1 van ${BUNDEL_PAD}. Zonder banner regenereert de ` +
        `plugin het bestand nooit meer. Zet hem terug via git; nooit weghalen.`,
    );
  }
  const ontbrekend = [...toolnamen].filter((n) => !bundel.includes(`"${n}"`));
  if (ontbrekend.length > 0) {
    fouten.push(
      `Toolnamen uit ${BRON_MAP} ontbreken in de bundel: ${
        ontbrekend.join(", ")
      }. ` +
        `Vermoedelijk een stub van een Windows-build. Draai 'npm run bundle:mcp'.`,
    );
  }
  return fouten;
}

/** Eerste verschil tussen twee bundels, of `null` als ze (genormaliseerd) gelijk zijn. */
export function vergelijkBundels(
  bestaand: string,
  vers: string,
): string | null {
  const a = normaliseer(bestaand).split("\n");
  const b = normaliseer(vers).split("\n");
  if (a.join("\n") === b.join("\n")) return null;
  const i = a.findIndex((regel, n) => regel !== b[n]);
  return `De gecommitte bundel wijkt af van een verse build (${a.length} tegenover ${b.length} regels, ` +
    `eerste verschil op regel ${(i === -1 ? a.length : i) + 1}).`;
}

function zoekOmhoog(start: string, rel: string[]): string[] {
  const gevonden: string[] = [];
  for (let dir = resolve(start);; dir = dirname(dir)) {
    const p = join(dir, "node_modules", ...rel);
    if (existsSync(p)) gevonden.push(p);
    if (dirname(dir) === dir) return gevonden;
  }
}

/** In een git-worktree staan de pakketten hoger; npm nestelt esbuild onder de SDK, bun hoist hem. */
function vindSdkEnEsbuild(root: string): { sdk: string; esbuild: string } {
  const sdkPkg =
    zoekOmhoog(root, ["@lovable.dev", "mcp-js", "package.json"])[0];
  if (!sdkPkg) {
    throw new Error(
      "@lovable.dev/mcp-js niet gevonden; draai eerst een install",
    );
  }
  const sdk = dirname(sdkPkg);
  const esbuild = [
    join(sdk, "node_modules", "esbuild", "lib", "main.js"),
    ...zoekOmhoog(root, ["esbuild", "lib", "main.js"]),
  ]
    .find((p) => existsSync(p));
  if (!esbuild) {
    throw new Error("esbuild niet gevonden; draai eerst een install");
  }
  return { sdk, esbuild };
}

/** Een Vite-alias zoals `config.resolve.alias` hem na normalisatie geeft. */
export interface ViteAlias {
  find: string | RegExp;
  replacement: string;
}

/**
 * Exact de aliaslogica van de Lovable-plugin (`applyViteAliases`): een RegExp vervangt,
 * een string matcht het hele pad of `find + "/"`. Geeft `undefined` zonder treffer.
 */
export function pasAliasToe(
  pad: string,
  aliases: readonly ViteAlias[],
): string | undefined {
  for (const { find, replacement } of aliases) {
    if (find instanceof RegExp) {
      if (find.test(pad)) return pad.replace(find, replacement);
    } else if (pad === find || pad.startsWith(find + "/")) {
      return replacement + pad.slice(find.length);
    }
  }
  return undefined;
}

/**
 * Aliassen uit `compilerOptions.paths` van tsconfig.json (`"@/*": ["./src/*"]` wordt
 * `@` naar `<root>/src`). Voor de CLI en de pre-commit-hook, die de Vite-config niet
 * kennen; in Vite zelf komen de aliassen uit `config.resolve.alias`, net als bij de
 * plugin. Zonder dit werd `@/lib/x` een `npm:@/lib/x`-import (Billara, 13 sep 2026).
 */
export function aliasesUitTsconfig(root: string): ViteAlias[] {
  let tekst: string;
  try {
    tekst = readFileSync(join(root, "tsconfig.json"), "utf8");
  } catch {
    return [];
  }
  // deno-lint-ignore no-explicit-any
  let cfg: any;
  try {
    cfg = JSON.parse(tekst);
  } catch {
    try {
      cfg = JSON.parse(
        tekst.replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "")
          .replace(/,(\s*[}\]])/g, "$1"),
      );
    } catch {
      return [];
    }
  }
  const opts = cfg?.compilerOptions ?? {};
  const basis = resolve(root, opts.baseUrl ?? ".");
  const aliases: ViteAlias[] = [];
  for (const [patroon, doelen] of Object.entries(opts.paths ?? {})) {
    const doel = Array.isArray(doelen) ? doelen[0] : undefined;
    if (
      typeof doel !== "string" || !patroon.endsWith("/*") ||
      !doel.endsWith("/*")
    ) continue;
    aliases.push({
      find: patroon.slice(0, -2),
      replacement: resolve(basis, doel.slice(0, -2)),
    });
  }
  return aliases;
}

export interface BouwResultaat {
  pad: string;
  inhoud: string;
  gewijzigd: boolean;
  projectRef: string;
}

/**
 * Bouwt de bundel zoals de plugin, en schrijft hem enkel weg bij een verschil.
 * `schrijf: false` bouwt zonder de schijf te raken.
 */
export async function bouwMcpBundel(
  projectRoot: string,
  opties: { schrijf?: boolean; aliases?: ViteAlias[] } = {},
): Promise<BouwResultaat> {
  const root = resolve(projectRoot);
  const aliases = opties.aliases ?? aliasesUitTsconfig(root);
  const { sdk, esbuild } = vindSdkEnEsbuild(root);
  // require, geen import(): esbuild is CommonJS, en Deno laadt dat niet via import().
  const { build } = createRequire(join(root, "package.json"))(esbuild);
  const sdkVersie: string =
    JSON.parse(readFileSync(join(sdk, "package.json"), "utf8")).version;
  const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));
  const versies: Record<string, string> = {
    ...pkg.peerDependencies,
    ...pkg.devDependencies,
    ...pkg.dependencies,
  };

  const env = leesEnv(root);
  if (!env.VITE_SUPABASE_PROJECT_ID) {
    throw new Error(
      "VITE_SUPABASE_PROJECT_ID ontbreekt; zonder projectref klopt de OAuth-issuer niet",
    );
  }
  const define: Record<string, string> = {
    "import.meta.env": JSON.stringify(env),
  };
  for (const [k, v] of Object.entries(env)) {
    if (/^[A-Za-z_$][\w$]*$/.test(k)) {
      define[`import.meta.env.${k}`] = JSON.stringify(v);
    }
  }

  const result = await build({
    stdin: {
      contents: ENTRY,
      resolveDir: root,
      sourcefile: "lovable-mcp-supabase-entry.ts",
      loader: "ts",
    },
    bundle: true,
    write: false,
    metafile: true,
    format: "esm",
    platform: "neutral",
    target: "esnext",
    absWorkingDir: root,
    logLevel: "silent",
    define,
    plugins: [{
      // Zelfde volgorde als de plugin: eerst Vite-aliassen, dan bare imports extern.
      name: "lovable-mcp-resolve-vite-aliases",
      // deno-lint-ignore no-explicit-any
      setup(b: any) {
        b.onResolve(
          { filter: /.*/ },
          (
            args: {
              path: string;
              importer: string;
              kind: string;
              resolveDir: string;
              pluginData?: { viteAliasResolved?: boolean };
            },
          ) => {
            if (args.pluginData?.viteAliasResolved) return null;
            if (
              args.path === "@lovable.dev/mcp-js" ||
              args.path.startsWith("@lovable.dev/mcp-js/")
            ) return null;
            const vervangen = pasAliasToe(args.path, aliases);
            if (vervangen === undefined) return null;
            return b.resolve(vervangen, {
              kind: args.kind,
              importer: args.importer,
              resolveDir: args.resolveDir,
              pluginData: { viteAliasResolved: true },
            });
          },
        );
      },
    }, {
      name: "lovable-mcp-externalize-bare-as-npm",
      // deno-lint-ignore no-explicit-any
      setup(b: any) {
        b.onResolve({ filter: /.*/ }, (args: { path: string }) => {
          const p = args.path;
          if (isLokaalPad(p)) return null;
          if (/^(npm|node|jsr|https?|data):/.test(p)) {
            return { path: p, external: true };
          }
          return { path: npmSpecifier(p, versies, sdkVersie), external: true };
        });
      },
    }],
  });

  const pad = join(root, BUNDEL_PAD);
  const inhoud = BANNER + result.outputFiles[0].text;
  let bestaand: string | undefined;
  try {
    bestaand = readFileSync(pad, "utf8");
  } catch {
    bestaand = undefined;
  }
  const gewijzigd = bestaand !== inhoud;
  if (gewijzigd && opties.schrijf !== false) writeFileSync(pad, inhoud, "utf8");
  return {
    pad,
    inhoud,
    gewijzigd,
    projectRef: String(env.VITE_SUPABASE_PROJECT_ID),
  };
}

export interface Controle {
  inOrde: boolean;
  fouten: string[];
}

/**
 * Alle controles, zonder iets te schrijven en zonder te exiten: banner, toolnamen en
 * gelijkheid met een verse build. Een repo zonder `src/lib/mcp` is in orde.
 */
export async function controleerMcpBundel(
  projectRoot: string,
): Promise<Controle> {
  const root = resolve(projectRoot);
  if (!existsSync(join(root, BRON_MAP))) return { inOrde: true, fouten: [] };
  const pad = join(root, BUNDEL_PAD);
  if (!existsSync(pad)) {
    return {
      inOrde: false,
      fouten: [
        `${BUNDEL_PAD} ontbreekt. Draai 'npm run bundle:mcp' en commit het resultaat.`,
      ],
    };
  }
  const bestaand = readFileSync(pad, "utf8");
  const fouten = controleerInhoud(
    bestaand,
    toolnamenUitMap(join(root, BRON_MAP)),
  );
  try {
    const { inhoud } = await bouwMcpBundel(root, { schrijf: false });
    const verschil = vergelijkBundels(bestaand, inhoud);
    if (verschil) {
      fouten.push(
        `${verschil} Handwerk in ${BUNDEL_PAD}? Breng de wijziging aan in ${BRON_MAP}/, ` +
          `draai 'npm run bundle:mcp' en commit beide.`,
      );
    }
  } catch (err) {
    fouten.push(
      `Kon de bundel niet herbouwen om te vergelijken: ${
        (err as Error).message
      }. ` +
        `Draai eerst een install; zonder herbouw is deze controle blind.`,
    );
  }
  return { inOrde: fouten.length === 0, fouten };
}

/**
 * Vite-plugin die de bundel na de Lovable-plugin herbouwt (configResolved, buildStart
 * en bij wijzigingen in `src/lib/mcp` in dev). Zet hem ná `mcpPlugin()`.
 */
// deno-lint-ignore no-explicit-any
export function mcpBundelHerstelPlugin(opties: { root: string }): any {
  const root = opties.root;
  let bezig: Promise<void> | null = null;
  let viteAliases: ViteAlias[] | undefined;
  const herstel = (aanleiding: string): Promise<void> => {
    bezig = (bezig ?? Promise.resolve())
      .catch(() => {})
      .then(async () => {
        try {
          const { gewijzigd } = await bouwMcpBundel(
            root,
            viteAliases ? { aliases: viteAliases } : {},
          );
          if (gewijzigd) {
            console.log(`[mcp-bundel] ${BUNDEL_PAD} herbouwd (${aanleiding})`);
          }
        } catch (err) {
          console.error(
            `[mcp-bundel] herbouw mislukt (${aanleiding}): ${
              (err as Error).message
            }`,
          );
          throw err;
        }
      });
    return bezig;
  };
  return {
    name: "holie-mcp-bundel-herstel",
    // deno-lint-ignore no-explicit-any
    configResolved: (config: any) => {
      const alias = config?.resolve?.alias;
      if (Array.isArray(alias)) {
        viteAliases = alias.map(({ find, replacement }: ViteAlias) => ({
          find,
          replacement,
        }));
      }
      return herstel("configResolved");
    },
    buildStart: () => herstel("buildStart"),
    // deno-lint-ignore no-explicit-any
    configureServer(server: any) {
      server.watcher.on("change", (bestand: string) => {
        if (bestand.split("\\").join("/").includes(`/${BRON_MAP}/`)) {
          herstel(`wijziging ${bestand}`).catch(() => {});
        }
      });
    },
  };
}
